services:
  postgres:
    image: postgres:17
    container_name: dbserver
    environment:
      POSTGRES_USER: "postgres"
      POSTGRES_PASSWORD: "pg123"
      POSTGRES_DB: "primarydb"
    volumes:
      - postgres_data:/var/lib/postgresql/data
    ports:
      - "5432:5432"
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U postgres"]
      interval: 10s
      timeout: 5s
      retries: 5
    networks:
      - internal
    logging:
      driver: "json-file"
      options:
        max-size: "10m"      
        max-file: "3"
    
  api:
    image: cecilieelkjaer/minitwit-api:latest
    build:
      context: .
      dockerfile: src/Chirp.Api/Dockerfile
    container_name: apiserver
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
      - ENV DOTNET_RUNNING_IN_CONTAINER="true"
      - ConnectionStrings__DefaultConnection=Host=dbserver;Database=primarydb;Username=postgres;Password=pg123
    volumes:
      - dataprotection_keys:/app/keys
    ports:
      - "5000:8080"
    depends_on:
      postgres: 
        condition: service_healthy
    networks:
      - internal
    logging:
      driver: "json-file"
      options:
        max-size: "10m"
        max-file: "3"

  web:
    image: cecilieelkjaer/minitwit-web:latest
    build:
      context: .
      dockerfile: src/Chirp.Web/Dockerfile
    container_name: webserver
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
      - ENV DOTNET_RUNNING_IN_CONTAINER="true"
      - ConnectionStrings__DefaultConnection=Host=dbserver;Database=primarydb;Username=postgres;Password=pg123
    volumes:
      - dataprotection_keys:/app/keys
    ports:
      - "5001:8080"
    depends_on:
      postgres: 
        condition: service_healthy
    networks:
      - internal
    labels:
      logging: "promtail"
    logging: 
      driver: "json-file"
      options:
        max-size: "10m"      
        max-file: "3"        

  prometheus:
    image: cecilieelkjaer/prometheus_image:latest
    build:
      dockerfile: ./Dockerfile
      context: ./monitoring/prometheus
    container_name: prometheus
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
      - ENV DOTNET_RUNNING_IN_CONTAINER="true"
      - ConnectionStrings__DefaultConnection=Host=dbserver;Database=primarydb;Username=postgres;Password=pg123
    command:
      - "--config.file=/etc/prometheus/prometheus.yml"
    ports:
      - "9090:9090"
    networks:
      - internal
    labels:
      logging: "promtail"
    logging:
      driver: "json-file"
      options:
        max-size: "10m"
        max-file: "3"
  
  loki:
    image: grafana/loki:3.6.7
    container_name: loki
    ports:
      - "3100:3100"
    volumes:
      - ./loki/loki-config.yml:/etc/loki/local-config.yaml
      - loki-data:/loki
    command: -config.file=/etc/loki/local-config.yaml
    networks:
      - internal
    restart: unless-stopped
    logging:
      driver: "json-file"
      options:
        max-size: "10m"
        max-file: "3"

  alloy:
    image: grafana/alloy:latest
    container_name: alloy
    volumes:
      - ./alloy/config.alloy:/etc/alloy/config.alloy
      - /var/run/docker.sock:/var/run/docker.sock
      - /var/lib/docker/containers:/var/lib/docker/containers:ro
    command: run --server.http.listen-addr=0.0.0.0:12345 /etc/alloy/config.alloy
    networks:
      - internal
    depends_on:
      - loki
    restart: unless-stopped
    logging:
      driver: "json-file"
      options:
        max-size: "10m"
        max-file: "3"

  grafana:
    image: cecilieelkjaer/grafana_image:latest
    build:
      dockerfile: ./Dockerfile
      context: ./monitoring/grafana
    container_name: grafana
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
      - ENV DOTNET_RUNNING_IN_CONTAINER="true"
      - ConnectionStrings__DefaultConnection=Host=dbserver;Database=primarydb;Username=postgres;Password=pg123
    ports:
      - "3000:3000"
    networks:
      - internal
    volumes:
      - grafana-storage:/var/lib/grafana
    depends_on:
      - loki
    restart: unless-stopped
    logging:
      driver: "json-file"
      options:
        max-size: "10m"
        max-file: "3"

volumes:
  grafana-storage: {}
  postgres_data:
  dataprotection_keys:
  loki-data:

networks:
  internal:
    driver: bridge
    name: internal
    
