services:
  api:
    image: cecilieelkjaer/minitwit-api:latest
    build:
      context: .
      dockerfile: src/Chirp.Api/Dockerfile
    container_name: apiserver
    environment:
      - ASPNETCORE_ENVIRONMENT=Production
      - ConnectionStrings__DefaultConnection=${DB_CONNECTION}
    ports:
      - "5000:8080"
    networks:
      - app_internal
    logging:
      driver: "json-file"
      options:
        max-size: "10m"
        max-file: "3"

  web:
    image: cecilieelkjaer/minitwit-web:latest
    build:
      context: .
      dockerfile: src/Chirp.Web/Dockerfile
    container_name: webserver
    environment:
      - ASPNETCORE_ENVIRONMENT=Production
      - ConnectionStrings__DefaultConnection=${DB_CONNECTION}
    ports:
      - "5001:8080"
    networks:
      - app_internal
    labels:
      logging: "promtail"
    logging: 
      driver: "json-file"
      options:
        max-size: "10m"      
        max-file: "3"        

  prometheus:
    image: cecilieelkjaer/prometheus_image:latest
    build:
      dockerfile: ./Dockerfile
      context: ./monitoring/prometheus
    container_name: prometheus
    environment:
      - ASPNETCORE_ENVIRONMENT=Production
      - ConnectionStrings__DefaultConnection=${DB_CONNECTION}
    command:
      - "--config.file=/etc/prometheus/prometheus.yml"
    ports:
      - "9090:9090"
    networks:
      - app_internal
    labels:
      logging: "promtail"
    logging:
      driver: "json-file"
      options:
        max-size: "10m"
        max-file: "3"
  
  loki:
    image: cecilieelkjaer/loki:latest
    build:
      dockerfile: ./Dockerfile
      context: ./loki/
    container_name: loki
    ports:
      - "3100:3100"
    volumes:
      - loki-data:/loki
    command: -config.file=/etc/loki/loki-config.yml
    networks:
      - app_internal
    restart: unless-stopped
    logging:
      driver: "json-file"
      options:
        max-size: "10m"
        max-file: "3"

  alloy:
    image: cecilieelkjaer/alloy:latest
    build:
      dockerfile: ./Dockerfile
      context: ./alloy/
    container_name: alloy
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
      - /var/lib/docker/containers:/var/lib/docker/containers:ro
    command: run --server.http.listen-addr=0.0.0.0:12345 /etc/alloy/config.alloy
    networks:
      - app_internal
    depends_on:
      - loki
    restart: unless-stopped
    logging:
      driver: "json-file"
      options:
        max-size: "10m"
        max-file: "3"

  grafana:
    image: cecilieelkjaer/grafana_image:latest
    build:
      dockerfile: ./Dockerfile
      context: ./monitoring/grafana
    container_name: grafana
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
      - ConnectionStrings__DefaultConnection=${DB_CONNECTION}
    ports:
      - "3000:3000"
    networks:
      - app_internal
    volumes:
      - grafana-storage:/var/lib/grafana
    depends_on:
      - loki
    restart: unless-stopped
    logging:
      driver: "json-file"
      options:
        max-size: "10m"
        max-file: "3"

volumes:
  grafana-storage: {}
  loki-data:

networks:
  app_internal:
    driver: bridge
    name: app_internal
    
