services:
  postgres:
    environment:
      POSTGRES_USER: "postgres"
      POSTGRES_PASSWORD: "pg123"
      POSTGRES_DB: "primarydb"
    volumes:
      - postgres_data:/var/lib/postgresql/data

  migrate:
    environment:
      - ConnectionStrings__DefaultConnection=Host=host.docker.internal;Database=primarydb;Username=postgres;Password=pg123
    extra_hosts:
        - "host.docker.internal:host-gateway"

  api: 
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
      - ConnectionStrings__DefaultConnection=Host=host.docker.internal;Database=primarydb;Username=postgres;Password=pg123
    depends_on:
      migrate:
        condition: service_completed_successfully
    extra_hosts:
        - "host.docker.internal:host-gateway"

  web:
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
      - ConnectionStrings__DefaultConnection=Host=host.docker.internal;Database=primarydb;Username=postgres;Password=pg123
    depends_on:
      migrate:
        condition: service_completed_successfully
    extra_hosts:
        - "host.docker.internal:host-gateway"

volumes:
  postgres_data: