/*
 * Minitwit API
 *
 * Minitwit API
 *
 * The version of the OpenAPI document: 1.0
 * 
 * Generated by: https://openapi-generator.tech
 */

using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Mvc;
using Swashbuckle.AspNetCore.Annotations;
using Newtonsoft.Json;
using Org.OpenAPITools.Attributes;
using Org.OpenAPITools.Models;
using Chirp.Infrastructure;
using Chirp.Core;
using System.Threading.Tasks;
using System.Linq;
using Microsoft.AspNetCore.Identity;

namespace Chirp.API.Controllers
{
    /// <summary>
    /// 
    /// </summary>
    [Authorize(Policy = "SimulatorAuth")]
    [ApiController]
    public class MinitwitApiController : ControllerBase
    {
        private readonly IAuthorRepository _authorRepository;
        private readonly ICheepRepository _cheepRepository;
        private readonly IGlobalIntRepository _globalIntRepository;
        private readonly UserManager<Author> _userManager;

        /// <summary>
        /// Constructor for MinitwitApiController. Dependency Injection of IAuthorRepository and ICheepRepository is used to access the data layer.
        /// </summary>
        public MinitwitApiController(
            IAuthorRepository authorRepository,
            ICheepRepository cheepRepository,
            IGlobalIntRepository globalIntRepository,
            UserManager<Author> userManager)
        {
            _authorRepository = authorRepository;
            _cheepRepository = cheepRepository;
            _globalIntRepository = globalIntRepository;
            _userManager = userManager;
        }

        /// <summary>
        /// 
        /// </summary>
        /// <remarks>Get list of users followed by the given user.  - Query param &#x60;?no&#x3D;&#x60; limits result count. - Optionally updates a &#39;latest&#39; global value via &#x60;?latest&#x3D;&#x60; query param.</remarks>
        /// <param name="username"></param>
        /// <param name="latest">Optional: &#x60;latest&#x60; value to update</param>
        /// <param name="no">Optional: &#x60;no&#x60; limits result count</param>
        /// <response code="200">Success</response>
        /// <response code="403">Unauthorized - Must include correct Authorization header</response>
        /// <response code="404">User not found (no response body)</response>
        [HttpGet]
        [Route("/fllws/{username}")]
        [ValidateModelState]
        [SwaggerOperation("GetFollow")]
        [SwaggerResponse(statusCode: 200, type: typeof(FollowsResponse), description: "Success")]
        [SwaggerResponse(statusCode: 403, type: typeof(ErrorResponse), description: "Unauthorized - Must include correct Authorization header")]
        public virtual async Task<IActionResult> GetFollow([FromRoute(Name = "username")][Required] string username, [FromQuery(Name = "latest")] int? latest, [FromQuery(Name = "no")] int? no)
        {
            if (latest is int value)
            {
                await _globalIntRepository.Put("latest", value);
            }

            Author? author = await _authorRepository.FindAuthorWithNameNullable(username);
            if (author is null)
            {
                return NotFound();
            }

            IEnumerable<Author> follows = await _authorRepository.GetFollowing(author.Id);
            IEnumerable<string> names = follows.Take(no ?? int.MaxValue).Select(f => f.Name);

            return Ok(new FollowsResponse
            {
                Follows = [.. names],
            });
        }

        /// <summary>
        /// 
        /// </summary>
        /// <remarks>Returns the latest ID saved</remarks>
        /// <response code="200">Success</response>
        /// <response code="500">Internal Server Error</response>
        [HttpGet]
        [Route("/latest")]
        [ValidateModelState]
        [SwaggerOperation("GetLatestValue")]
        [SwaggerResponse(statusCode: 200, type: typeof(LatestValue), description: "Success")]
        [SwaggerResponse(statusCode: 500, type: typeof(ErrorResponse), description: "Internal Server Error")]
        public virtual async Task<IActionResult> GetLatestValue()
        {
            if (await _globalIntRepository.Get("latest") is int value)
            {
                return Ok(new LatestValue { Latest = value });
            }

            return NotFound();
        }

        /// <summary>
        /// 
        /// </summary>
        /// <remarks>Get recent messages.  - Filters out flagged messages - Returns a list of recent messages (max defined by &#x60;?no&#x3D;&#x60; param) - Optionally updates a &#39;latest&#39; global value via &#x60;?latest&#x3D;&#x60; query param.</remarks>
        /// <param name="latest">Optional: &#x60;latest&#x60; value to update</param>
        /// <param name="no">Optional: &#x60;no&#x60; limits result count</param>
        /// <response code="200">Success</response>
        /// <response code="403">Unauthorized - Must include correct Authorization header</response>
        [HttpGet]
        [Route("/msgs")]
        [ValidateModelState]
        [SwaggerOperation("GetMessages")]
        [SwaggerResponse(statusCode: 200, type: typeof(List<Message>), description: "Success")]
        [SwaggerResponse(statusCode: 403, type: typeof(ErrorResponse), description: "Unauthorized - Must include correct Authorization header")]
        public virtual async Task<IActionResult> GetMessages([FromQuery(Name = "latest")] int? latest, [FromQuery(Name = "no")] int? no)
        {
            if (latest is int value)
            {
                await _globalIntRepository.Put("latest", value);
            }

            List<CheepDTO> cheeps = await _cheepRepository.GetCheeps(1, no ?? int.MaxValue);
            return Ok(cheeps.Select(c => new Message
            {
                Content = c.Text,
                PubDate = c.TimeStamp,
                User = c.AuthorName,
            }));
        }

        /// <summary>
        /// 
        /// </summary>
        /// <remarks>Get messages for a specific user.  - Returns messages authored by the specified user - Filtered by unflagged - Returns a list of recent messages for the user (max defined by &#x60;?no&#x3D;&#x60; param) - Optionally updates a &#39;latest&#39; global value via &#x60;?latest&#x3D;&#x60; query param.</remarks>
        /// <param name="username"></param>
        /// <param name="latest">Optional: &#x60;latest&#x60; value to update</param>
        /// <param name="no">Optional: &#x60;no&#x60; limits result count</param>
        /// <response code="200">Success</response>
        /// <response code="403">Unauthorized - Must include correct Authorization header</response>
        /// <response code="404">User not found (no response body)</response>
        [HttpGet]
        [Route("/msgs/{username}")]
        [ValidateModelState]
        [SwaggerOperation("GetMessagesPerUser")]
        [SwaggerResponse(statusCode: 200, type: typeof(List<Message>), description: "Success")]
        [SwaggerResponse(statusCode: 403, type: typeof(ErrorResponse), description: "Unauthorized - Must include correct Authorization header")]
        public virtual async Task<IActionResult> GetMessagesPerUser([FromRoute(Name = "username")][Required] string username, [FromQuery(Name = "latest")] int? latest, [FromQuery(Name = "no")] int? no)
        {
            if (latest is int value)
            {
                await _globalIntRepository.Put("latest", value);
            }

            Author? author = await _authorRepository.FindAuthorWithNameNullable(username);
            if (author is null)
            {
                return NotFound();
            }

            IEnumerable<Cheep> cheeps = await _cheepRepository.GetCheepsByAuthor(author.Id);
            return Ok(cheeps.Select(c => new Message
            {
                Content = c.Text,
                PubDate = c.TimeStamp.ToString(),
                User = username,
            }));
        }

        /// <summary>
        /// 
        /// </summary>
        /// <remarks>Follow or unfollow a user on behalf of &#x60;username&#x60;.  - Body must contain either &#x60;follow: &lt;user&gt;&#x60; or &#x60;unfollow: &lt;user&gt;&#x60;</remarks>
        /// <param name="username"></param>
        /// <param name="payload"></param>
        /// <param name="latest">Optional: &#x60;latest&#x60; value to update</param>
        /// <response code="204">No Content</response>
        /// <response code="403">Unauthorized - Must include correct Authorization header</response>
        /// <response code="404">User not found (no response body)</response>
        [HttpPost]
        [Route("/fllws/{username}")]
        [Consumes("application/json")]
        [ValidateModelState]
        [SwaggerOperation("PostFollow")]
        [SwaggerResponse(statusCode: 403, type: typeof(ErrorResponse), description: "Unauthorized - Must include correct Authorization header")]
        public virtual async Task<IActionResult> PostFollow([FromRoute(Name = "username")][Required] string username, [FromBody] FollowAction payload, [FromQuery(Name = "latest")] int? latest)
        {
            if (latest is int value)
            {
                await _globalIntRepository.Put("latest", value);
            }

            Author? follower = await _authorRepository.FindAuthorWithNameNullable(username);
            if (follower is null)
            {
                return NotFound();
            }

            if (payload.Follow is string followeeName)
            {
                Author? followee = await _authorRepository.FindAuthorWithNameNullable(followeeName);
                if (followee is null)
                {
                    return NotFound();
                }

                await _authorRepository.FollowUserAsync(follower.Id, followee.Id);
                return NoContent();
            }

            if (payload.Unfollow is string unfolloweeName)
            {
                Author? unfollowee = await _authorRepository.FindAuthorWithNameNullable(unfolloweeName);
                if (unfollowee is null)
                {
                    return NotFound();
                }

                await _authorRepository.UnFollowUserAsync(follower.Id, unfollowee.Id);
                return NoContent();
            }

            return BadRequest();
        }

        /// <summary>
        /// 
        /// </summary>
        /// <remarks>Post a new message as a specific user.  - Message must include &#x60;content&#x60; in the body - Stored with timestamp and &#x60;flagged&#x3D;0&#x60; - Returns empty body on success - Optionally updates a &#39;latest&#39; global value via &#x60;?latest&#x3D;&#x60; query param.</remarks>
        /// <param name="username"></param>
        /// <param name="payload"></param>
        /// <param name="latest">Optional: &#x60;latest&#x60; value to update</param>
        /// <response code="204">No Content</response>
        /// <response code="403">Unauthorized - Must include correct Authorization header</response>
        [HttpPost]
        [Route("/msgs/{username}")]
        [Consumes("application/json")]
        [ValidateModelState]
        [SwaggerOperation("PostMessagesPerUser")]
        [SwaggerResponse(statusCode: 403, type: typeof(ErrorResponse), description: "Unauthorized - Must include correct Authorization header")]
        public virtual async Task<IActionResult> PostMessagesPerUser([FromRoute(Name = "username")][Required] string username, [FromBody] PostMessage payload, [FromQuery(Name = "latest")] int? latest)
        {
            if (latest is int value)
            {
                await _globalIntRepository.Put("latest", value);
            }

            Author? author = await _authorRepository.FindAuthorWithNameNullable(username);
            if (author == null)
            {
                return NotFound();
            }

            var cheep = new Cheep
            {
                AuthorId = author.Id,
                Text = payload.Content,
                TimeStamp = DateTime.UtcNow,
                Author = author
            };

            await _cheepRepository.SaveCheep(cheep, author);
            return NoContent();
        }

        /// <summary>
        /// 
        /// </summary>
        /// <remarks>Register a new user. - Optionally updates a &#39;latest&#39; global value via &#x60;?latest&#x3D;&#x60; query param.</remarks>
        /// <param name="payload"></param>
        /// <param name="latest">Optional: &#x60;latest&#x60; value to update</param>
        /// <response code="204">No Content</response>
        /// <response code="400">Bad Request | Possible reasons:  - missing username  - invalid email  - password missing  - username already taken</response>
        [HttpPost]
        [Route("/register")]
        [Consumes("application/json")]
        [ValidateModelState]
        [SwaggerOperation("PostRegister")]
        [SwaggerResponse(statusCode: 400, type: typeof(ErrorResponse), description: "Bad Request | Possible reasons:  - missing username  - invalid email  - password missing  - username already taken")]
        public virtual async Task<IActionResult> PostRegister([FromBody] RegisterRequest payload, [FromQuery(Name = "latest")] int? latest)
        {
            if (latest is int value)
            {
                await _globalIntRepository.Put("latest", value);
            }

            var user = new Author
            {
                Email = payload.Email,
                UserName = payload.Email,
                Name = payload.Username,
                Cheeps = [],
            };

            IdentityResult result = await _userManager.CreateAsync(user, payload.Pwd);

            if (result.Succeeded)
            {
                return NoContent();
            }

            return BadRequest(result.Errors);
        }

        /// <summary>
        /// Deletes a user from the database. Currently only used for testing. 
        /// </summary>
        /// <param name="username"></param>
        /// <response code="204">No Content</response>
        /// <response code="400">Bad Request</response>
        [AllowAnonymous]
        [HttpGet]
        [Route("/delete/{username}")]
        [Consumes("application/json")]
        [ValidateModelState]
        public virtual async Task<IActionResult> Delete([FromRoute(Name = "username")][Required] string username)
        {
            Author? author = await _authorRepository.FindAuthorWithNameNullable(username);
            if (author is null)
            {
                return NotFound();
            }

            IdentityResult result = await _userManager.DeleteAsync(author);
            
            if (result.Succeeded)
            {
                return NoContent();
            }

            return BadRequest(result.Errors);
        }
    }
}
