{
 "title": "MiniTwit Logging Dashboard",
 "time": { "from": "now-6h", "to": "now" },
 "panels": [
  {
   "title": "Alloy logs",
   "type": "logs",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 0 },
   "targets": [
    {
     "direction": "backward",
     "expr": "{container=\"alloy\"}"
    }
   ]
  },
  {
   "title": "Prometheus logs",
   "type": "logs",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 8 },
   "targets": [
    {
     "direction": "backward",
     "expr": "{container=\"prometheus\"}"
    }
   ]
  },
  {
   "title": "Loki logs",
   "type": "logs",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 16 },
   "targets": [
    {
     "direction": "backward",
     "expr": "{container=\"loki\"}"
    }
   ]
  },
  {
   "title": "DB logs",
   "type": "logs",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 24 },
   "targets": [
    {
     "direction": "backward",
     "expr": "{container=\"dbserver\"}"
    }
   ]
  },
  {
   "title": "Grafana logs",
   "type": "logs",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 32 },
   "targets": [
    {
     "direction": "backward",
     "expr": "{container=\"grafana\"}"
    }
   ]
  },
  {
   "title": "Api logs",
   "type": "logs",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 40 },
   "targets": [
    {
     "direction": "backward",
     "expr": "{container=\"apiserver\"}"
    }
   ]
  },
  {
   "title": "Web logs",
   "type": "logs",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 48 },
   "targets": [
    {
     "direction": "backward",
     "expr": "{container=\"webserver\"}"
    }
   ]
  }
 ]
}