// Copyright (c) devops-gruppe-connie. All rights reserved.

/*
 * Minitwit API
 *
 * Minitwit API
 *
 * The version of the OpenAPI document: 1.0
 *
 * Generated by: https://openapi-generator.tech
 */

using System;
using System.Collections.Generic;
using System.ComponentModel;
using System.ComponentModel.DataAnnotations;
using System.Linq;
using System.Runtime.Serialization;
using System.Text;
using Newtonsoft.Json;
using Org.OpenAPITools.Converters;

namespace Org.OpenAPITools.Models
{
    /// <summary>
    ///
    /// </summary>
    [DataContract]
    public partial class Message : IEquatable<Message>
    {
        /// <summary>
        /// Gets or sets text content of the message.
        /// </summary>
        /// <value>Text content of the message.</value>
        /* <example>Hello, World!</example> */
        [DataMember(Name = "content", EmitDefaultValue = false)]
        public string? Content { get; set; }

        /// <summary>
        /// Gets or sets publication date/time of the message.
        /// </summary>
        /// <value>Publication date/time of the message.</value>
        /* <example>2019-12-01 12:00:00</example> */
        [DataMember(Name = "pub_date", EmitDefaultValue = false)]
        public string? PubDate { get; set; }

        /// <summary>
        /// Gets or sets username of the message author.
        /// </summary>
        /// <value>Username of the message author.</value>
        /* <example>Helge</example> */
        [DataMember(Name = "user", EmitDefaultValue = false)]
        public string? User { get; set; }

        /// <summary>
        /// Returns the string presentation of the object.
        /// </summary>
        /// <returns>String presentation of the object.</returns>
        public override string ToString()
        {
            var sb = new StringBuilder();
            sb.Append("class Message {\n");
            sb.Append("  Content: ").Append(this.Content).Append("\n");
            sb.Append("  PubDate: ").Append(this.PubDate).Append("\n");
            sb.Append("  User: ").Append(this.User).Append("\n");
            sb.Append("}\n");
            return sb.ToString();
        }

        /// <summary>
        /// Returns the JSON string presentation of the object.
        /// </summary>
        /// <returns>JSON string presentation of the object.</returns>
        public string ToJson()
        {
            return JsonConvert.SerializeObject(this, Formatting.Indented);
        }

        /// <summary>
        /// Returns true if objects are equal.
        /// </summary>
        /// <param name="obj">Object to be compared.</param>
        /// <returns>Boolean.</returns>
        public override bool Equals(object obj)
        {
            if (obj is null)
            {
                return false;
            }

            if (ReferenceEquals(this, obj))
            {
                return true;
            }

            return obj.GetType() == this.GetType() && this.Equals((Message)obj);
        }

        /// <summary>
        /// Returns true if Message instances are equal.
        /// </summary>
        /// <param name="other">Instance of Message to be compared.</param>
        /// <returns>Boolean.</returns>
        public bool Equals(Message other)
        {
            if (other is null)
            {
                return false;
            }

            if (ReferenceEquals(this, other))
            {
                return true;
            }

            return
                (
                    this.Content == other.Content ||
                    (this.Content != null &&
                    this.Content.Equals(other.Content))) &&
                (
                    this.PubDate == other.PubDate ||
                    (this.PubDate != null &&
                    this.PubDate.Equals(other.PubDate))) &&
                (
                    this.User == other.User ||
                    (this.User != null &&
                    this.User.Equals(other.User)));
        }

        /// <summary>
        /// Gets the hash code.
        /// </summary>
        /// <returns>Hash code.</returns>
        public override int GetHashCode()
        {
            unchecked // Overflow is fine, just wrap
            {
                var hashCode = 41;

                // Suitable nullity checks etc, of course :)
                if (this.Content != null)
                {
                    hashCode = (hashCode * 59) + this.Content.GetHashCode();
                }

                if (this.PubDate != null)
                {
                    hashCode = (hashCode * 59) + this.PubDate.GetHashCode();
                }

                if (this.User != null)
                {
                    hashCode = (hashCode * 59) + this.User.GetHashCode();
                }

                return hashCode;
            }
        }

#pragma warning disable 1591

        public static bool operator ==(Message left, Message right)
        {
            return Equals(left, right);
        }

        public static bool operator !=(Message left, Message right)
        {
            return !Equals(left, right);
        }

#pragma warning restore 1591
    }
}
