// Copyright (c) devops-gruppe-connie. All rights reserved.

/*
 * Minitwit API
 *
 * Minitwit API
 *
 * The version of the OpenAPI document: 1.0
 *
 * Generated by: https://openapi-generator.tech
 */

using System;
using System.Collections.Generic;
using System.ComponentModel;
using System.ComponentModel.DataAnnotations;
using System.Linq;
using System.Runtime.Serialization;
using System.Text;
using Newtonsoft.Json;
using Org.OpenAPITools.Converters;

namespace Org.OpenAPITools.Models
{
    /// <summary>
    ///
    /// </summary>
    [DataContract]
    public partial class RegisterRequest : IEquatable<RegisterRequest>
    {
        /// <summary>
        /// Gets or sets username.
        /// </summary>
        /// <value>Username.</value>
        [Required]
        [DataMember(Name = "username", EmitDefaultValue = false)]
        public string Username { get; set; }

        /// <summary>
        /// Gets or sets email address.
        /// </summary>
        /// <value>Email address.</value>
        [Required]
        [DataMember(Name = "email", EmitDefaultValue = false)]
        public string Email { get; set; }

        /// <summary>
        /// Gets or sets password.
        /// </summary>
        /// <value>Password.</value>
        [Required]
        [DataMember(Name = "pwd", EmitDefaultValue = false)]
        public string Pwd { get; set; }

        /// <summary>
        /// Returns the string presentation of the object.
        /// </summary>
        /// <returns>String presentation of the object.</returns>
        public override string ToString()
        {
            var sb = new StringBuilder();
            sb.Append("class RegisterRequest {\n");
            sb.Append("  Username: ").Append(this.Username).Append("\n");
            sb.Append("  Email: ").Append(this.Email).Append("\n");
            sb.Append("  Pwd: ").Append(this.Pwd).Append("\n");
            sb.Append("}\n");
            return sb.ToString();
        }

        /// <summary>
        /// Returns the JSON string presentation of the object.
        /// </summary>
        /// <returns>JSON string presentation of the object.</returns>
        public string ToJson()
        {
            return JsonConvert.SerializeObject(this, Formatting.Indented);
        }

        /// <summary>
        /// Returns true if objects are equal.
        /// </summary>
        /// <param name="obj">Object to be compared.</param>
        /// <returns>Boolean.</returns>
        public override bool Equals(object obj)
        {
            if (obj is null)
            {
                return false;
            }

            if (ReferenceEquals(this, obj))
            {
                return true;
            }

            return obj.GetType() == this.GetType() && this.Equals((RegisterRequest)obj);
        }

        /// <summary>
        /// Returns true if RegisterRequest instances are equal.
        /// </summary>
        /// <param name="other">Instance of RegisterRequest to be compared.</param>
        /// <returns>Boolean.</returns>
        public bool Equals(RegisterRequest other)
        {
            if (other is null)
            {
                return false;
            }

            if (ReferenceEquals(this, other))
            {
                return true;
            }

            return
                (
                    this.Username == other.Username ||
                    (this.Username != null &&
                    this.Username.Equals(other.Username))) &&
                (
                    this.Email == other.Email ||
                    (this.Email != null &&
                    this.Email.Equals(other.Email))) &&
                (
                    this.Pwd == other.Pwd ||
                    (this.Pwd != null &&
                    this.Pwd.Equals(other.Pwd)));
        }

        /// <summary>
        /// Gets the hash code.
        /// </summary>
        /// <returns>Hash code.</returns>
        public override int GetHashCode()
        {
            unchecked // Overflow is fine, just wrap
            {
                var hashCode = 41;

                // Suitable nullity checks etc, of course :)
                if (this.Username != null)
                {
                    hashCode = (hashCode * 59) + this.Username.GetHashCode();
                }

                if (this.Email != null)
                {
                    hashCode = (hashCode * 59) + this.Email.GetHashCode();
                }

                if (this.Pwd != null)
                {
                    hashCode = (hashCode * 59) + this.Pwd.GetHashCode();
                }

                return hashCode;
            }
        }

#pragma warning disable 1591

        public static bool operator ==(RegisterRequest left, RegisterRequest right)
        {
            return Equals(left, right);
        }

        public static bool operator !=(RegisterRequest left, RegisterRequest right)
        {
            return !Equals(left, right);
        }

#pragma warning restore 1591
    }
}
