---
name: Continuous Deployment

on:
  push:
    # Run workflow every time something is pushed to the main branch
    branches:
      - main
    tags:
      - 'v*.*.*'
  pull_request:
    branches:
      - main
  workflow_dispatch:

jobs:
  test: # Tests non-playwright tests
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repo
        uses: actions/checkout@v4
      
      - name: Setup .NET
        uses: actions/setup-dotnet@v4
        with:
          dotnet-version: 8.0.x
      
      - name: Restore dependencies
        run: dotnet restore

      - name: Build
        run: dotnet build --no-restore -c Release

      - name: Run non-Playwright tests
        run: dotnet test --no-build -c Release --verbosity minimal test/Chirp.Infrastructure.Test/Chirp.Infrastructure.Test.csproj

  test-playwright:
    runs-on: ubuntu-latest
    container:
      image: mcr.microsoft.com/playwright/dotnet:v1.50.0-noble
    steps:
      - name: Checkout repo
        uses: actions/checkout@v4

      - name: Restore dependencies
        run: dotnet restore

      - name: Build
        run: dotnet build --no-restore -c Release

      - name: Run Playwright tests
        run: dotnet test --no-build -c Release --verbosity minimal test/Chirp.Web.Playwright.Test/Chirp.Web.Playwright.Test.csproj 
        env:
          PLAYWRIGHT_BROWSERS_PATH: /ms-playwright
  
  security-scan:
    runs-on: ubuntu-latest
    permissions:
      security-events: write
    steps:
      - name: Checkout repo
        uses: actions/checkout@v4

      - name: Setup .NET
        uses: actions/setup-dotnet@v4
        with:
          dotnet-version: |
            3.1.x
            8.0.x

      - name: Set up Security Code Scan
        uses: security-code-scan/security-code-scan-add-action@5f75674efc0abc4d41aa8cf3f1706ed5fe9365dd # v1.2

      - name: Build
        run: |
          dotnet restore
          dotnet build

      - name: Convert sarif for uploading to GitHub
        uses: security-code-scan/security-code-scan-results-action@cdb3d5e639054395e45bf401cba8688fcaf7a687 # v1

      - name: Merge sarif files
        run: |
          sarif merge /home/runner/work/devops-minitwit/results/*.sarif --merge-runs --output-file /home/runner/work/devops-minitwit/results/merged.sarif
          rm /home/runner/work/devops-minitwit/results/[0-9]*.sarif

      - name: Upload sarif
        uses: github/codeql-action/upload-sarif@v4
        with:
          sarif_file: /home/runner/work/devops-minitwit/results/merged.sarif
          category: security-code-scan

  release:
    needs: [test, test-playwright]
    runs-on: ubuntu-latest
    permissions:
      contents: write
    if: startsWith(github.ref, 'refs/tags/v')

    steps:
      - name: Checkout repo
        uses: actions/checkout@v4
      
      - name: Setup .NET
        uses: actions/setup-dotnet@v4
        with:
          dotnet-version: 8.0.x

      # Build, create a release and create zip files for the release. 
      - name: Create ZIP files
        run: |
          # Create a release directory to hold all platform-specific releases
          mkdir release

          # Publish for Linux (default)
          dotnet publish -c Release -o ./release/linux
          cd release/linux
          zip -r ../../my_project_linux.zip .

          # Publish for macOS
          cd ../../
          dotnet publish -r osx-x64 -c Release -o ./release/mac
          cd release/mac
          zip -r ../../my_project_mac.zip .

          # Publish for Windows
          cd ../../
          dotnet publish -r win-x64 -c Release -o ./release/win
          cd release/win
          zip -r ../../my_project_win.zip .

      - name: Create release
        uses: softprops/action-gh-release@v2.0.8
        with:
          files: |
            my_project_linux.zip
            my_project_mac.zip
            my_project_win.zip

  push-images:
    needs: [test, test-playwright]
    runs-on: ubuntu-latest
    if: github.event_name == 'push' && (github.ref == 'refs/heads/main' || github.ref == 'refs/heads/master')

    steps:
      - name: Checkout repo
        uses: actions/checkout@v4

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Log in to Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}

      - name: Build images
        run: docker compose -f docker-compose-app.yml -f docker-compose-db.yml build

      - name: Install Trivy
        uses: aquasecurity/setup-trivy@3fb12ec12f41e471780db15c232d5dd185dcb514 # v0.2.6
        with:
          version: v0.69.3

      - name: Scan Docker images with Trivy
        run: |
          IMAGES=$(docker compose -f docker-compose-app.yml -f docker-compose-db.yml config --images)
          for IMAGE in $IMAGES; do
            echo "Scanning $IMAGE..."
            trivy image --exit-code 1 --severity CRITICAL,HIGH --ignore-unfixed --ignorefile .trivyignore --scanners vuln "$IMAGE"
          done

      - name: Push images
        run: docker compose -f docker-compose-app.yml -f docker-compose-db.yml push

  pull-images-db:
    needs: [push-images]
    runs-on: ubuntu-latest

    steps:
      - name: Update docker-compose-db.yml on database server
        run: |
          echo "${{ secrets.SSH_KEY }}" > ssh_key
          chmod 600 ssh_key
          scp -i ssh_key -o StrictHostKeyChecking=no docker-compose-db.yml ${{ secrets.SSH_USER }}@${{ secrets.DB_HOST }}:/app/
          rm ssh_key

      - name: Pull via SSH
        uses: appleboy/ssh-action@v1.0.3
        with:
          host: ${{ secrets.DB_HOST }}
          username: ${{ secrets.SSH_USER }}
          key: ${{ secrets.SSH_KEY }}
          script: |
            cd /app
            docker compose -f docker-compose-db.yml pull
            docker compose -f docker-compose-db.yml up -d --remove-orphans
    
  pull-images-app:
    needs: [push-images]
    runs-on: ubuntu-latest

    strategy:
      matrix:
        host: ${{ fromJson(vars.APP_SERVER_IPS) }}

    steps:
      - name: Update docker-compose-app.yml on any app/minitwit server
        run: |
          echo "${{ secrets.SSH_KEY }}" > ssh_key
          chmod 600 ssh_key
          scp -i ssh_key -o StrictHostKeyChecking=no docker-compose-app.yml ${{ secrets.SSH_USER }}@${{ matrix.host }}:/app/
          rm ssh_key

      - name: Pull via SSH
        uses: appleboy/ssh-action@v1.0.3
        with:
          host: ${{ matrix.host }}
          username: ${{ secrets.SSH_USER }}
          key: ${{ secrets.SSH_KEY }}
          script: |
            cd /app
            docker compose -f docker-compose-app.yml pull
            docker compose -f docker-compose-app.yml up -d --remove-orphans